CREATE OR REPLACE TRIGGER TRI_SM_FLOW_DEPARTMENT
BEFORE INSERT ON SM_FLOW_DEPARTMENT
FOR EACH ROW

when (NEW.DBID IS NULL)
BEGIN
    SELECT SEQ_SM_FLOW_DEPARTMENT_ID.NEXTVAL INTO:NEW.DBID FROM DUAL;
END;