CREATE OR REPLACE TRIGGER TRI_EVENT_PROCESS_DETAIL
BEFORE INSERT ON SM_EVENT_PROCESS_DETAIL
FOR EACH ROW

when (NEW.DBID IS NULL)
BEGIN
    SELECT SEQ_EVENT_PROCESS_ID.NEXTVAL INTO:NEW.DBID FROM DUAL;
END;